spring:
  application:
    name: payments-backend

  datasource:
    url: jdbc:postgresql://localhost:5490/ironvault
    username: ironvault
    password: ironvault

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.flywaydb: INFO

server:
  port: 8080